### ISSUE TITLE
After rename fixes compile fails

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/GreenBeretDS#1]
EmuMenu.c
/home/demetris/Desktop/Development/GreenBeretDS/arm9/source/Shared/EmuMenu.c: In function 'flickSet':
/home/demetris/Desktop/Development/GreenBeretDS/arm9/source/Shared/EmuMenu.c:793:9: error: 'gFlicker' undeclared (first use in this function); did you mean 'g_flicker'?
  793 |         gFlicker++;
      |         ^~~~~~~~
      |         g_flicker
/home/demetris/Desktop/Development/GreenBeretDS/arm9/source/Shared/EmuMenu.c:793:9: note: each undeclared identifier is reported only once for each function it appears in
/home/demetris/Desktop/Development/GreenBeretDS/arm9/source/Shared/EmuMenu.c:796:17: error: 'gTwitch' undeclared (first use in this function); did you mean 'g_twitch'?
  796 |                 gTwitch = 0;
      |                 ^~~~~~~
      |                 g_twitch
make[2]: *** [/opt/devkitpro/devkitARM/base_rules:85: EmuMenu.o] Error 1
make[1]: *** [Makefile:107: build] Error 2
make[1]: Leaving directory '/home/demetris/Desktop/Development/GreenBeretDS/arm9'
make: *** [Makefile:41: arm9/GreenBeretDS.elf] Error 2

**Comment by FluBBaOfWard** [comment]
Pushed new source.

**Comment by Ntemis** [comment]
Missed this
FileHandling.c
/home/demetris/Desktop/Development/GreenBeretDS/arm9/source/FileHandling.c:8:10: fatal error: Filehandling.h: No such file or directory
    8 | #include "Filehandling.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

**Comment by FluBBaOfWard** [comment]
Pushed again.

**Comment by Ntemis** [comment]
gtg
